### ISSUE TITLE
Non-English environment log error occurs

### ISSUE THREAD

**Issue by lycc193** [Neosinf/StardewDruid#2]
Although there is an error, it seems to have no impact on use and the fix is quite simple

```
[13:39:59 ERROR StardewDruid] This mod failed in the Content.AssetRequested event. Technical details: 
ArgumentException: Requested value 'Effigy.zh-CN' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse[TEnum](ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, TEnum& result)
   at System.Enum.Parse[TEnum](String value)
   at StardewDruid.Mod.OnAssetRequested(Object sender, AssetRequestedEventArgs e) in E:\Code\MyCode\StardewDruid\StardewDruid\Mod.cs:line 203
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(Action`2 invoke) in SMAPI\Framework\Events\ManagedEvent.cs:line 139
[13:39:59 ERROR StardewDruid] This mod failed in the Content.AssetRequested event. Technical details: 
ArgumentException: Requested value 'Effigy_international' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse[TEnum](ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, TEnum& result)
   at System.Enum.Parse[TEnum](String value)
   at StardewDruid.Mod.OnAssetRequested(Object sender, AssetRequestedEventArgs e) in E:\Code\MyCode\StardewDruid\StardewDruid\Mod.cs:line 203
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(Action`2 invoke) in SMAPI\Framework\Events\ManagedEvent.cs:line 139
```

[`string characterId = e.Name.ToString().Replace("StardewDruid.Characters.", "");`](https://github.com/Neosinf/StardewDruid/blob/7fa9169fd6bbe296db13779eec3fa00723856af5/StardewDruid/Mod.cs#L201)
->
`string characterId = e.Name.ToString().Replace("StardewDruid.Characters.", "").Split('.')[0];`

It's better to rewrite this logic, but making this change directly can also solve the error.

**Comment by Neosinf** [comment]
I'm lost as to this error. What is appending those additional characters to the asset string?

**Comment by Neosinf** [comment]
Ah well I don't quite understand it but now that I've loaded the game in a different language I get the same error
